set guicursor=a:blinkon0
set guifont=Monaco:h14
set background=dark

" Disable toolbar on startup
set guioptions-=T

" fullscreen maximizes vertically AND horizontally
set fuoptions=maxvert,maxhorz

" Disable bell.
set vb t_vb=
